name: Auto Generate Unit Tests

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.java'

jobs:
  test-generation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Flask API in Background
      run: |
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        nohup python app.py & sleep 5

    - name: Run Test Generator Script
      run: |
        python test_generator.py

    - name: Upload Generated Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-cases-report
        path: generated_tests_report.md
